import { UserProfile, Project, TestimonialItem } from './types';

export const INITIAL_PROFILE: UserProfile = {
  name: "Zakaria Boulagjame",
  title: "Forward Deployed Engineer & Systems Architect",
  titleFr: "Forward Deployed Engineer & Architecte Systèmes",
  titleRu: "Forward Deployed Engineer & Архитектор Систем",
  tagline: "From Applied Physics to Mission-Critical Systems",
  taglineFr: "De la Physique aux Systèmes Critiques",
  taglineRu: "От прикладной физики к критическим системам",
  bio: "Forward Deployed Engineer bridging applied physics rigor with mission-critical systems: efficiency is mandatory, friction is eliminated. I engineer fault-tolerant platforms, high-reliability transaction engines, and operational AI swarms built directly for enterprise field execution and tangible financial impact.",
  bioFr: "Forward Deployed Engineer appliquant la rigueur de la physique aux systèmes critiques : l'efficacité est obligatoire, la friction est éliminée. Je conçois et déploie des architectures logicielles durcies, des moteurs transactionnels haute disponibilité et des agents IA opérationnels à fort impact financier.",
  bioRu: "Forward Deployed Engineer, переносящий строгость прикладной физики в критические системы: эффективность обязательна, трение устранено. Я проектирую и развертываю отказоустойчивые архитектуры, надежные транзакционные ядра и боевых ИИ-агентов с прямым финансовым результатом.",
  linkedInUrl: "https://www.linkedin.com/in/zakaria-boulagjame/",
  avatarUrl: "https://github.com/Boulagjame-dev.png"
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'cecot-pos',
    title: "CECOT-POS System",
    titleFr: "Système CECOT-POS",
    titleRu: "Система CECOT-POS",
    category: 'Retail & POS',
    description: "Cloud Point of Sale & Inventory engine with live smartphone camera barcode pairing. Features instant Z-closure cash reporting, quote generation, and Supabase real-time synchronization.",
    descriptionFr: "Moteur de caisse cloud et gestion de stocks avec appairage caméra smartphone en direct. Intègre clôtures de caisse (Z), génération de devis et synchronisation temps réel Supabase.",
    descriptionRu: "Облачная касса и складской учет с мгновенным сканированием штрихкодов через камеру смартфона. Z-отчеты в реальном времени, генерация смет и синхронизация с Supabase.",
    tags: ["React 18", "Supabase", "Tailwind CSS", "HTML5 QR/Barcode", "Webhooks"],
    imageUrl: "/projects/cecot-pos.jpg",
    repoUrl: "https://github.com/Boulagjame-dev/CECOT-POS",
    businessOutcome: "0 Cash Discrepancy & 12h/week saved in stock auditing",
    businessOutcomeFr: "0 Écart de Caisse & 12h/semaine économisées sur les stocks",
    businessOutcomeRu: "0 расхождений в кассе и 12ч/нед. экономии на инвентаризации",
    caseStudy: "Eliminated dedicated barcode scanner hardware with zero-install smartphone camera pairing and automated stock level alerts.",
    caseStudyFr: "Élimination des terminaux coûteux grâce à l'appairage direct smartphone et notifications de seuils d'inventaire.",
    caseStudyRu: "Устранение затрат на сканеры благодаря интеграции веб-камер смартфонов и оповещениям об остатках."
  },
  {
    id: 'cecot-vitrine',
    title: "CECOT Vitrine & Local GEO",
    titleFr: "CECOT Vitrine & Moteur GEO",
    titleRu: "CECOT Vitrine & Локальный GEO-движок",
    category: 'SaaS & Web Apps',
    description: "High-performance web vitrine and lead acquisition engine for Morocco's premier reprography hub. Structured Schema.org JSON-LD for Google AI Overviews (GEO), 76+ live products catalogue, and large-format architectural print calculator.",
    descriptionFr: "Site vitrine haute performance et acquisition de leads pour centre de reprographie à Casablanca. Schema.org JSON-LD pour Google AI Overviews (GEO), catalogue 76+ articles et calculateur de tirages architecturaux A0/A1.",
    descriptionRu: "Корпоративная витрина и движок локального ранжирования (GEO/SEO) в Касабланке. Schema.org JSON-LD для Google AI, каталог из 76+ позиций и калькулятор архитектурной печати A0/A1.",
    tags: ["Vanilla JS", "Node.js", "SEO / GEO", "Schema.org", "Tailwind CSS"],
    imageUrl: "/projects/cecot-vitrine.jpg",
    repoUrl: "https://github.com/Boulagjame-dev/cecot-vitrine",
    liveUrl: "https://github.com/Boulagjame-dev/cecot-vitrine",
    businessOutcome: "+85% Local visibility & Automated architectural quote intake",
    businessOutcomeFr: "+85% Visibilité locale & Qualification automatique des devis plans",
    businessOutcomeRu: "+85% локальной видимости и автоматизация расчетов смет",
    caseStudy: "Deployed optimized semantic structure and localized schema graph to dominate local search rankings and automate B2B print orders.",
    caseStudyFr: "Structure sémantique ultra-rapide et balisage Schema.org géolocalisé pour dominer les requêtes locales et capter les commandes B2B.",
    caseStudyRu: "Семантическая разметка Schema.org и алгоритмический калькулятор для захвата B2B-заказов."
  },
  {
    id: 'fofinette-pos',
    title: "Fofinette by Zeyna — POS & AI Suite",
    titleFr: "Fofinette by Zeyna — POS & Suite IA",
    titleRu: "Fofinette by Zeyna — POS & ИИ-комплекс",
    category: 'AI & Automation',
    description: "Smart retail & culinary POS connected to an autonomous n8n backend: automated invoice OCR extraction (Gemini Vision), real-time Telegram sales telemetry, and instant stock threshold alerts.",
    descriptionFr: "Caisse tactile connectée à un backend d'automatisation n8n : extraction OCR IA des factures fournisseurs (Gemini Vision), alertes ventes et stocks critiques sur Telegram.",
    descriptionRu: "Сенсорная кассовая система с бэкендом на n8n: OCR-распознавание счетов через Gemini Vision, телеметрия продаж в Telegram и критические оповещения об остатках.",
    tags: ["React", "Supabase", "n8n", "Gemini Vision", "Telegram Bot API"],
    imageUrl: "/projects/fofinette.jpeg",
    repoUrl: "https://github.com/Boulagjame-dev/fofinette-pos",
    businessOutcome: "10x Faster supplier invoice intake & Real-time financial alerts",
    businessOutcomeFr: "Traitement factures 10x plus rapide & Télémesure financière en direct",
    businessOutcomeRu: "Обработка счетов в 10 раз быстрее и прямая телеметрия в Telegram",
    caseStudy: "Eliminated manual accounting overhead with automated multi-modal invoice digitization and real-time Telegram notifications.",
    caseStudyFr: "Suppression totale de la saisie comptable manuelle grâce à l'OCR IA multimodal couplé aux webhooks Telegram.",
    caseStudyRu: "Полное устранение ручного ввода счетов благодаря мультимодальному OCR и вебхукам Telegram."
  },
  {
    id: 'coop-saas',
    title: "Coop-SaaS Maroc (Loi 112-12)",
    titleFr: "Coop-SaaS Maroc (Loi 112-12)",
    titleRu: "Coop-SaaS Maroc (Закон 112-12)",
    category: 'SaaS & Web Apps',
    description: "Multi-tenant B2B governance and financial compliance system engineered for Moroccan cooperatives under Law 112-12 (ODCO / INDH). Complete RBAC matrix with PostgreSQL Row-Level Security.",
    descriptionFr: "Solution SaaS B2B multi-tenant de gouvernance et conformité légale pour coopératives marocaines (Loi 112-12 / ODCO / INDH). Matrice RBAC stricte et Row-Level Security PostgreSQL.",
    descriptionRu: "B2B SaaS-платформа корпоративного управления и юридического соответствия для кооперативов (ODCO / INDH). Матрица RBAC и безопасность на уровне строк в PostgreSQL (RLS).",
    tags: ["PostgreSQL", "Supabase RLS", "Multi-tenancy", "TypeScript", "Tailwind CSS"],
    imageUrl: "/projects/coop-saas.jpg",
    businessOutcome: "100% Legal ODCO compliance & Full INDH subsidy traceability",
    businessOutcomeFr: "100% Conformité statutaire ODCO & Traçabilité complète INDH",
    businessOutcomeRu: "100% соответствие закону и прозрачный учет субсидий INDH",
    caseStudy: "Engineered strict tenant isolation and automated generation of mandatory statutory registers and member voting protocols.",
    caseStudyFr: "Isolation étanche des données par coopérative avec génération automatique des registres légaux obligatoires.",
    caseStudyRu: "Изоляция мультитенантных данных кооперативов с защитой аудита и генерацией обязательных реестров."
  },
  {
    id: 'leslions',
    title: "Les Lions — InsurTech Comparator",
    titleFr: "Les Lions — Comparateur InsurTech",
    titleRu: "Les Lions — InsurTech Компаратор",
    category: 'SaaS & Web Apps',
    description: "French B2C insurance comparison platform (Health, Auto, Loan borrower). Powered by friendly mascots Leo & Lea, dynamic intake funnels, instant lead valuation, and automated broker CRM injection.",
    descriptionFr: "Comparateur B2C d'assurances en France (Santé, Auto, Emprunteur). Porté par les mascottes Léo & Léa, entonnoirs dynamiques, scoring en temps réel et injection CRM courtier.",
    descriptionRu: "B2C компаратор страхования во Франции (здоровье, авто, заемщики). Персонализированные маскоты Лео и Леа, мгновенный скоринг заявок и квалификация лидов.",
    tags: ["Next.js 16", "React 19", "Turborepo", "TypeScript", "Zod", "Tailwind CSS"],
    imageUrl: "/projects/leslions.png",
    businessOutcome: "65% Faster funnel completion & High-intent lead generation",
    businessOutcomeFr: "Tunnel 65% plus rapide & Qualification de leads haute valeur",
    businessOutcomeRu: "Время прохождения воронки сокращено на 65% и квалификация лидов",
    caseStudy: "Constructed an ultra-fast monorepo architecture with Zod schema verification and interactive insurance quoting workflows.",
    caseStudyFr: "Monorepo haute performance avec validation Zod rigoureuse et tunnels de tarification multi-compagnies.",
    caseStudyRu: "Высокоскоростная монорепозиторная архитектура с валидацией Zod и интерактивным расчетом полисов."
  },
  {
    id: 'rolland-assurances',
    title: "Rolland Assurances Hub",
    titleFr: "Écosystème Rolland Assurances",
    titleRu: "Rolland Assurances — ИИ-Маркетинг",
    category: 'AI & Automation',
    description: "Digital brokerage portal combined with an autonomous multi-agent marketing machine (MicroHard CAI/MGI framework). Automates Google Ads campaign iteration, compliance checking, and senior health quotes.",
    descriptionFr: "Portail digital de courtage combiné à une architecture multi-agents IA (framework MicroHard CAI/MGI) pour automatiser les campagnes Google Ads et les devis santé senior.",
    descriptionRu: "Агентный комплекс генерации спроса и оптимизации рекламы для страхового брокера. Мультиагентный анализ креативов, интеграция с Google Ads API и автопилот.",
    tags: ["React", "MicroHard AI", "Google Ads API", "Workflow Automation", "Tailwind CSS"],
    imageUrl: "/projects/rolland-assurances.svg",
    repoUrl: "https://github.com/Boulagjame-dev/RA-V2",
    businessOutcome: "Lower customer acquisition cost & Hands-free ad optimization",
    businessOutcomeFr: "Réduction du coût d'acquisition client & Optimisation publicitaire 24/7",
    businessOutcomeRu: "-38% стоимости привлечения клиента (CAC) и автопилот 24/7",
    caseStudy: "Deployed autonomous AI agent swarms to continuously craft, test, and optimize acquisition hooks for insurance products.",
    caseStudyFr: "Déploiement d'agents IA autonomes pour générer et tester des accroches marketing tout en respectant la conformité.",
    caseStudyRu: "Автономные рои ИИ-агентов для непрерывной генерации и A/B-тестирования рекламных хуков."
  },
  {
    id: 'etsy-pod',
    title: "Etsy Merch Factory (Zero API Cost)",
    titleFr: "Usine E-commerce Print-on-Demand",
    titleRu: "Etsy Merch Factory ($0 API Cost)",
    category: 'AI & Automation',
    description: "Autonomous Print-on-Demand pipeline. Generates 4500x5400px transparent merchandise designs via headless Edge vector rendering, synced directly to Printify API and Etsy store through n8n.",
    descriptionFr: "Pipeline e-commerce Print-on-Demand autonome. Rendu vectoriel headless sous Edge (PNG 4500x5400px transparent natif), synchronisé avec l'API Printify et boutique Etsy via n8n.",
    descriptionRu: "Автономный конвейер Print-on-Demand: генерация векторного арта 4500×5400px через headless Edge, создание макапов через Printify API и публикация на Etsy через n8n.",
    tags: ["PowerShell", "Headless Edge", "Printify API", "Etsy API", "n8n"],
    imageUrl: "/projects/etsy-pod.jpg",
    businessOutcome: "$0 Design generation API cost & 100% Hands-off merchandise sync",
    businessOutcomeFr: "0$ de coût d'API image & Mise en vente 100% automatisée",
    businessOutcomeRu: "$0 затрат на API генерации и 100% автономная публикация",
    caseStudy: "Engineered headless browser rendering system delivering pixel-perfect typographic apparel without unpredictable AI image API costs.",
    caseStudyFr: "Remplacement des modèles d'images IA instables par un moteur de rendu vectoriel HTML/CSS ultra-précis.",
    caseStudyRu: "Замена дорогих ИИ-генераторов картинок детерминированным векторным рендерингом высокого разрешения."
  },
  {
    id: 'mymentor',
    title: "MyMentor OS",
    titleFr: "MyMentor OS",
    titleRu: "MyMentor OS — ИИ-Наставник",
    category: 'AI & Automation',
    description: "Adaptive AI learning platform automating 100% of user onboarding and dynamic curriculum generation. Scalable architecture for real-time personalized learning paths.",
    descriptionFr: "Plateforme d'apprentissage adaptatif automatisant 100% de l'onboarding et de la génération de parcours personnalisés en temps réel avec l'IA.",
    descriptionRu: "Адаптивная платформа обучения с оркестрацией нескольких LLM: автоматический онбординг, персонализированные учебные траектории и векторный RAG.",
    tags: ["React", "TypeScript", "Google Gemini API", "Supabase", "Tailwind CSS"],
    imageUrl: "https://placehold.co/800x600/120b2e/a3ffce?text=MyMentor+OS&font=montserrat",
    repoUrl: "https://github.com/Boulagjame-dev/MyMentor",
    businessOutcome: "+40% Student engagement & Fully automated curriculum scaling",
    businessOutcomeFr: "+40% d'engagement apprenant & Génération de cours 100% automatisée",
    businessOutcomeRu: "+40% вовлеченности студентов и полная персонализация обучения",
    caseStudy: "Designed dynamic learning paths and automated evaluation mechanisms powered by Gemini API and Supabase real-time data.",
    caseStudyFr: "Conception de parcours dynamiques et d'évaluation continue propulsés par l'API Gemini et Supabase.",
    caseStudyRu: "Динамические учебные треки и непрерывная оценка знаний на базе Gemini API и Supabase."
  },
  {
    id: 'modjex',
    title: "Modjex Smart Inventory",
    titleFr: "Modjex Smart Inventory",
    titleRu: "Modjex Smart Inventory",
    category: 'Retail & POS',
    description: "Real-time margin analysis and inventory intelligence dashboard. Replaced error-prone spreadsheets with automated CSV parsing and LLM catalog sanitization.",
    descriptionFr: "Tableau de bord de suivi des marges et valorisation des stocks en temps réel. Remplace les tableurs manuels par le parsing CSV automatisé et l'enrichissement par LLM.",
    descriptionRu: "Аналитическая панель учета маржинальности и склада. Замена таблиц Excel автоматическим парсингом CSV и нормализацией каталогов через LLM.",
    tags: ["React", "Data Visualization", "CSV Parsing", "Gemini API"],
    imageUrl: "https://placehold.co/800x600/120b2e/a3ffce?text=MODJEX&font=montserrat",
    repoUrl: "https://github.com/Boulagjame-dev/Modjex-Site",
    businessOutcome: "15+ Hours saved weekly & Total elimination of inventory mismatch",
    businessOutcomeFr: "15+ heures économisées par semaine & Zéro écart de catalogue",
    businessOutcomeRu: "15+ часов экономии еженедельно и ликвидация расхождений",
    caseStudy: "Integrated automated catalog ingestion and LLM-driven classification to unify multi-source retail supplies.",
    caseStudyFr: "Ingestion automatique de catalogues complexes et catégorisation assistée par IA.",
    caseStudyRu: "Автоматический импорт разрозненных каталогов поставщиков и классификация на базе ИИ."
  },
  {
    id: 'bizcard',
    title: "BizCard AI",
    titleFr: "BizCard AI",
    titleRu: "BizCard Batch AI",
    category: 'AI & Automation',
    description: "99% Precision batch lead extraction system. Transforms physical business cards into CRM-ready assets in seconds using Gemini Pro Vision.",
    descriptionFr: "Pipeline d'extraction de leads à 99% de précision à partir de cartes de visite physiques par lot via Gemini Pro Vision et synchronisation CRM.",
    descriptionRu: "Пакетная оцифровка визиток через Gemini Pro Vision с точностью 99%: извлечение контактов, валидация полей и мгновенный экспорт в CRM.",
    tags: ["React (TypeScript)", "Supabase", "Gemini Vision", "Tailwind CSS"],
    imageUrl: "https://placehold.co/800x600/120b2e/a3ffce?text=BizCard+AI&font=montserrat",
    repoUrl: "https://github.com/Boulagjame-dev/bizcard-batch",
    businessOutcome: "99% Extraction accuracy & Zero manual CRM data entry",
    businessOutcomeFr: "99% de précision OCR & Zéro saisie manuelle dans le CRM",
    businessOutcomeRu: "Точность извлечения 99% и исключение ручного ввода в CRM",
    caseStudy: "Leveraged multi-modal Gemini Vision to extract complex typography, corporate domains, and multilingual card data directly into CRM.",
    caseStudyFr: "Extraction fidèle de typographies complexes et formatage automatique pour import CRM instantané.",
    caseStudyRu: "Мультимодальное распознавание нетипичных шрифтов, контактов и сайтов с прямой синхронизацией."
  }
];

export const CLIENT_TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'rolland',
    author: "N. Rolland",
    role: "Founder & Managing Broker",
    roleFr: "Dirigeant Fondateur",
    roleRu: "Управляющий Директор",
    company: "Rolland Assurances",
    content: "Zakaria engineered our digital brokerage platform and automated our lead acquisition loops with remarkable rigor. Our acquisition cost per qualified senior health lead dropped by 38% while maintaining total compliance.",
    contentFr: "Zakaria a conçu notre portail de courtage et automatisé nos boucles d'acquisition avec une rigueur exemplaire. Notre coût par prospect senior qualifié a baissé de 38% tout en garantissant une conformité totale.",
    contentRu: "Закария разработал наш брокерский портал и автоматизировал воронки лидогенерации с исключительной точностью. Стоимость привлечения квалифицированного клиента снизилась на 38% при полном соблюдении регуляторных норм.",
    rating: 5,
    highlight: "-38% Acquisition Cost & High-Intent Leads",
    highlightFr: "-38% Coût d'Acquisition & Leads Hautement Qualifiés",
    highlightRu: "-38% CAC и поток целевых заявок"
  },
  {
    id: 'cecot',
    author: "Direction CECOT",
    role: "Operations & Retail Hub",
    roleFr: "Direction des Opérations",
    roleRu: "Дирекция по Операциям",
    company: "CECOT Casablanca",
    content: "The CECOT-POS system and local GEO optimization delivered immediate ROI. Being able to pair our phone cameras as instant barcode scanners saved us hundreds in hardware and saves our staff over 12 hours every week.",
    contentFr: "CECOT-POS et l'optimisation GEO locale ont généré un retour sur investissement immédiat. Pouvoir appairer nos smartphones en lecteur code-barres a évité des terminaux coûteux et nous fait gagner plus de 12 heures chaque semaine.",
    contentRu: "Система CECOT-POS и локальная GEO-оптимизация дали мгновенный ROI. Сканирование штрихкодов камерой телефона сэкономило средства на оборудовании и сохраняет нашей команде более 12 часов каждую неделю.",
    rating: 5,
    highlight: "0 Cash Error & 12h+ Saved Every Week",
    highlightFr: "0 Écart de Caisse & +12h Gagnées par Semaine",
    highlightRu: "0 ошибок в кассе и +12ч экономии в неделю"
  },
  {
    id: 'fofinette',
    author: "D. Zegrani",
    role: "Founder & Executive Director",
    roleFr: "Fondatrice & Direction",
    roleRu: "Основательница и Руководство",
    company: "Fofinette by Zeyna",
    content: "The automated n8n OCR invoice processing and instant Telegram alerts have completely removed our administrative bottlenecks. Invoices are parsed into Supabase in seconds with zero manual data entry.",
    contentFr: "L'OCR automatique des factures via n8n et les alertes Telegram instantanées ont totalement débloqué notre gestion. Les factures sont intégrées dans Supabase en quelques secondes sans aucune ressaisie manuelle.",
    contentRu: "Автоматическое OCR-распознавание счетов через n8n и мгновенные уведомления в Telegram полностью ликвидировали административную рутину. Счета вносятся в Supabase за секунды без ручного ввода.",
    rating: 5,
    highlight: "10x Faster Ingestion & Real-Time Telemetry",
    highlightFr: "Traitement 10x Plus Rapide & Visibilité Temps Réel",
    highlightRu: "Обработка в 10 раз быстрее и прямой контроль"
  }
];